name: Test addLabel Action

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize]

permissions:
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Add multiple Labels to PR or Issue
        uses: IamPekka058/addLabels@v2
        with:
          labels: |
            - hello
            - there

          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove multiple Labels from PR or Issue
        uses: ./
        with:
          labels: |
            - hello
            - there
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add single Label to PR or Issue
        uses: IamPekka058/addLabels@v2
        with:
          labels: hello

          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove single Label from PR or Issue 
        uses: ./
        with:
          labels: hello
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove Label (which is not present) from PR or Issue
        uses: ./
        with:
          labels: hello
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add single Label with spaces to PR or Issue
        uses: IamPekka058/addLabels@v2
        with:
          labels: 🧪 This is a test

          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove single Label with spaces from PR or Issue 
        uses: ./
        with:
          labels: 🧪 This is a test
          github_token: ${{ secrets.GITHUB_TOKEN }}
